[package]
name = "shellmark"
version = "0.1.0"
authors = ["Artem Pyanykh <artem.pyanykh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {version = "0.19", features = ["event-stream"]}
tui = {version = "0.14", default-features = false, features = ["crossterm"]}
tokio = {version = "1.1", features = ["full"]}
tokio-stream = "0.1.2"
futures = "0.3"
simsearch = "0.2"