name: Release

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true

jobs:
  build:
    name: Build the release on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - runner: windows-latest
            exe: shellmark.exe
          - runner: ubuntu-latest
            exe: shellmark
          - runner: macos-latest
            exe: shellmark
    steps:
      - uses: actions/checkout@v2
      - name: Setup rust toolchian
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Build the release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Upload the binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os.runner }}-${{ matrix.os.exe }}
          path: target/release/${{ matrix.os.exe }}
          if-no-files-found: error
  
  release:
    name: Create the release for ${{ matrix.os.runner }}
    needs: build
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - runner: windows-latest
            exe: shellmark.exe
            release_exe: shellmark-windows.exe
          - runner: ubuntu-latest
            exe: shellmark
            release_exe: shellmark-linux
          - runner: macos-latest
            exe: shellmark
            release_exe: shellmark-macos
    steps:
      - id: download
        name: Download the release binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.os.runner }}-${{ matrix.os.exe }}

      - name: Rename the binary
        shell: python
        run: |
          import os
          os.rename("${{ matrix.os.exe }}", "${{ matrix.os.release_exe }}")

      - name: Create a GH release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.os.release_exe }}
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.name }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

